# Example Docker Compose File
version: "3"
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    # expose database for the host if needed
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-openai:/var/lib/postgresql/data

volumes:
  postgres-openai:
